spring.application.name=Hotels
server.port=8092
spring.liquibase.change-log=classpath:db/changelog/db.changelog-master.xml
spring.jpa.hibernate.ddl-auto=validate
server.servlet.context-path=/property-view
spring.profiles.active=h2